- name: build solana
  become: true
  become_user: solana
  shell: "source /home/solana/.cargo/env && cd /mnt/{{ repo_dir }} && ./cargo stable build --release"
  args:
    chdir: "/mnt/{{ repo_dir }}"
    executable: /bin/bash
